# Site
name: "Samdisha's Personal Blog"
title: "Samdisha's Personal Blog"
description: "Live, Learn, Grow with me & my experiences."
logo: "assets/images/brand/logo.png"
favicon: "assets/images/brand/logo.ico"
url: "https://samdisha.me"
baseurl: ""
google_analytics: "G-DLH9VBNNPV"
# mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages", ".nojekyll"]
permalink: /:title
email: khunger.samdisha@gmail.com
instagram: https://instagram.com/samdisha_khunger/
staticman_url: https://comments.samdisha.me/v2/entry/samdishakhunger/blog/main/comments

# Authors
authors:
  samdisha:
    name: Samdisha
    display_name: Samdisha
    avatar: "assets/images/brand/avatar-samdisha.png"
    email: khunger.samdisha@gmail.com
    web: https://ko-fi.com/samdishakhunger
    instagram: https://instagram.com/samdisha_khunger/
    youtube: https://www.youtube.com/channel/UC9_JX_dvkBCfOlZ7FacYrBQ
    description: "I am gentle, quirky, childish adult girl, budding passion for blogging."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name.html"
    
# Pagination 
paginate: 9
paginate_path: "/page/:num"
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8114751086331659"
adsense-data-display-ad-slot: "5514529526"
adsense-data-infeed-ad-slot: "5514529526"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [Gemfile, Gemfile.lock, run.sh, run.bat, publish.sh, publish.bat]
